#!/bin/sh

LC_ALL=C
export LC_ALL

doit() {

	test -f configure.in || exit 0

echo `pwd`:

	if test -f po/Makefile.in.in
	then
		if test ! -f po/Makefile
		then
			cp po/Makefile.in.in po/Makefile
		fi
	fi

	if grep -q LT_INIT configure.in
	then
		libtoolize --force `if grep -q LIBLTDL configure.in ; then echo --ltdl; fi`

	fi
	aclocal || exit 1
	if grep -q AM_CONFIG_HEADER configure.in
	then
		autoheader || exit 1
	fi
	if grep -q AC_PROG_SYSCONFTOOL configure.in
	then
		sysconftoolize || exit 1
	fi
	if test -f AUTHORS -a -f NEWS -a -f README
	then
		automake --add-missing || exit 1
	else
		automake --foreign --add-missing || exit 1
	fi
	autoconf || exit 1

	for d in */.
	do
		( cd $d >/dev/null 2>&1 || continue; doit ) || exit 1
	done
}

doit
